{% set name = "scri" %}
{% set version = environ.get('GIT_DESCRIBE_TAG', 'untagged')|string|replace('-','_') %}
{% set build_number = environ.get('GIT_DESCRIBE_NUMBER', '0') %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: {{ environ.get('FEEDSTOCK_ROOT', '..') }}

build:
  noarch: python
  number: {{ build_number }}
  string: {{ [build_number, ('h' + PKG_HASH), environ.get('GIT_DESCRIBE_HASH', '')]|join('_') }}
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - numpy
    - scipy
    - h5py
    - numba
    - matplotlib
    - quaternion
    - spinsfast
    - spherical_functions
    - sxs

test:
  imports:
    - scri
  commands:
    - pytest
  requires:
    - pytest
    - pytest-azurepipelines
  source_files:
    - tests/

about:
 home: https://github.com/moble/scri
 license: MIT
 license_family: MIT
 license_file: LICENSE
