sudo: false

language: python

python:
  - "2.7"
  - "3.5"

install:
  - lsb_release -a
  - source auto_version/travis_install_conda.sh numpy scipy matplotlib numba pip pytest h5py;
  - conda config --add channels moble
  - conda install fftw quaternion spinsfast spherical_functions
  - python setup.py install

script:
  - python -c 'import scri; print(scri.version_info())'
  - py.test -s --run_slow_tests

after_success:
  # Change permissions for Anaconda deployment script
  - chmod +x ./.conda_deploy.sh

deploy:
  # Deploy to Anaconda.org
  - provider: script
    script: "./.conda_deploy.sh"
    skip_cleanup: true
