package:
  name: scri
  version: '1.0'

source:
  git_url: https://github.com/moble/scri.git

build:
  detect_binary_files_with_prefix: true
  script: python setup.py install

requirements:
  build:
    - python
    - numpy >=1.7

  run:
    - python
    - numpy >=1.7
    - scipy
    - matplotlib
    - h5py
    - pytest
    - numba
    - quaternion
    - spinsfast
    - spherical_functions

about:
  home: 'https://github.com/moble/scri'
  license: MIT
  summary: 'Python/numba code for manipulating time-dependent functions of spin-weighted spherical harmonics'
